---

- name: add neovim ppa
  become: yes
  become_user: root
  apt_repository: repo=ppa:neovim-ppa/unstable state=present

- name: install dependencies
  become: yes
  become_user: root
  async: 600
  poll: 0
  apt:
    name: "{{ base_packages }}"
    state: latest
    update_cache: true

- include: nvm.yml

- block:
  - name: find .vimrc if it exists
    find:
      paths: /home/vagrant
      patterns: ".vimrc"
    register: find_results

  - name: delete .vimrc if exists
    file:
      path: "{{ item['path'] }}"
      state: absent
    with_items: "{{ find_results['files'] }}"
    
  - name: add new .vimrc
    template:
      src: ../assets/.vimrc
      dest: /home/vagrant/.vimr

- name: install lvim
  shell: |
    echo 'to install lunarvim execute the following' && \
    echo 'bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)' && \
    echo 'config is under temp'
  register: command_output

- debug: 
    var: command_output.stdout_lines
